[project]
name = "cybersec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "ipykernel",
    "joblib",
    "matplotlib",
    "nbformat",
    "pandas",
    "plotly",
    "polars",
    "pyarrow",
    "pytest",
    "ruff>=0.14.14",
    "scikit-learn",
    "scipy",
    "seaborn",
    "uvicorn>=0.40.0",
    "xgboost",
]
